name: Run Tox

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - Training/Rest/**

env:
  WORKDIR: Training/Rest

jobs:
  tox:
    name: Run Tox
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tox
        run: pip install tox

      - name: Run tox
        working-directory: ${{ env.WORKDIR }}
        run: |
          echo "# Running Tox..." :rocket: >> $GITHUB_STEP_SUMMARY 2>&1
          tox >> $GITHUB_STEP_SUMMARY 2>&1